[package]
name = "lime-audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lime-core = { path = "../lime-core" }
symphonia.workspace = true
cpal.workspace = true
signalsmith-stretch.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
log.workspace = true
hound.workspace = true
